### ISSUE TITLE
Dudas instalación de HDRescuer

### ISSUE THREAD

**Issue by Albert-vill** [DomingoLopez/HDRescuer#19]
Buenas Domingo, Me llamo Alberto Villanueva y estoy realizando mi TFG sobre detección de estado en animales de
compañía usando dispositivos wearables con el profesor Francisco M. Garcia-Moreno. Para ellos estamos intentando usar tu app para conectarla a una pulsera empática y un reloj TicWatch E3 2749 sin mucho éxito. ¿Sería posible hacerte algunas preguntas sobre la instalación?

Gracias por tu tiempo,
Alberto.

**Comment by DomingoLopez** [comment]
Hola Alberto. 
Sin problema, dime qué es lo que ocurre. Yo he podido bajar el repo, y tal cual lo descomprimo lo importo en Android Studio y funciona bien. 
Tienes que hacer una serie de modificaciones en algunos ficheros del proyecto, como añadir el API KEY de la empatica en el archivo Common/Constants, así como referenciar bien la dirección del endpoint del servidor, en el String "DATA_RESCUER_API_GATEWAY". 

![indicar_empatica_api_key](https://user-images.githubusercontent.com/34646643/166721846-ef812bae-dbd5-4fb2-be43-678c109a37fc.png)

Sin hacer absolutamente nada me ha corrido en el emulador. Te aconsejo que no lo ejecutes en el emulador para probarlo ya que el tema del bluetooth no va muy bien en el emulador. Para ello conecta tu Android al ordenador y debería correrte la aplicación sin problemas. 

En cuanto al reloj, es necesario instalar la app "hdrescuerwatch" que también está en el proyecto en el reloj. Esto lo puedes hacer vía usb conectando el reloj al pc a través de la plataforma de carga del reloj. Tienes que tener el reloj vinculado con el dispositivo Android y con la aplicación "wearOS" también instalada en el Android.

Cualquier duda me escribes al correo "domin68914@gmail.com" y si quieres tenemos una pequeña video alguna tarde que puedas y vemos el problema.

Un saludo.

closes #19
